### ISSUE TITLE
Collision severity appears as undefined in popup

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/bikedata#27]
In the [collisions view](https://bikedata.cyclestreets.net/collisions/#15/51.5250/-0.1037/opencyclemap) the value **undefined** appears in the popup for severity:
<img width="221" alt="collision_severity_undefined" src="https://user-images.githubusercontent.com/361987/70060363-4dc48500-15da-11ea-9859-d1b025037dfb.png">

This is happening because of the following temporary code:
```javascript
                                       // Remove icon if present in data
                                       if (iconField) {
                                               if (feature.properties.hasOwnProperty(iconField)) {
                                                       delete feature.properties[iconField];
                                               }
                                       }
```
which is on the live server, injected this location: https://github.com/cyclestreets/Leaflet.LayerViewer/blob/20c9281e64b2ba6b7341eda96af2a3f9bc979311/src/Leaflet.LayerViewer.js#L2097

I don't know why that extra code is there (and I don't think I added it), but the severity does appear in the popup if it is removed.

**Comment by mvl22** [comment]
It's because the site is currently assuming that iconField is a field that you wouldn't normally then also show.

This assumption is clearly wrong, or needs to be configurable.

**Comment by mvl22** [comment]
The monkey-patched code is no longer present on the server, so this issue got resolved.
